name: CI

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
      - name: Install Dependencies
        run: cd modules/web && yarn install
      - name: Build apps-manage
        run: cd modules/web && yarn run build:ext apps-manage
      - name: Upload dist-file
        uses: actions/upload-artifact@v4
        with:
          name: dist-file
          path: |
            modules/web/extensions/apps-manage/dist
  

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Wait for build job to finish
        run: echo "Build job has completed successfully!"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Download dist-file
        uses: actions/download-artifact@v4
        with:
          name: dist-file
          path: modules/web/extensions/apps-manage/dist
      - name: tree
        run: ls  modules/web/extensions/apps-manage/dist
      - name: push docker images
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push kubesphere/apps-manage:${GITHUB_REF#refs/tags/}
