name: CI

on:
  push:
    tags:
      - '*'

jobs:
  lint:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
      - name: Install Dependencies
        run: cd modules/web && yarn install
      - name: Build apps-manage
        run: cd modules/web && yarn run build:ext apps-manage
      - name: Build Docker Image
        run: cd modules/web/extensions/apps-manage && docker build --tag=kubesphere/apps-manage:${GITHUB_REF#refs/tags/} .
      - name: Build and push docker images
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push kubesphere/apps-manage:${GITHUB_REF#refs/tags/}